### PR TITLE
Allow containers to have no exposed/forwarded port

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
Reading the Consular source code it looks like it'll handle the situation ok where no ports are defined.
I'm reluctant to update Consular with the move to Traefik coming up.

**Comment by smn** [comment]
Ready for review.

**Comment by miltontony** [comment]
You'll probably need a migration

**Comment by smn** [comment]
right, done, thanks!

**Comment by miltontony** [comment]
👍 🍰

**Pull request merged**
