### PR TITLE
enable restart button

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by calston** [comment]
:+1:

**Comment by smn** [comment]
Can we make this a POST button please? If not now then let's at least get a ticket for it. If one hits the back button the app will restart again.

**Comment by miltontony** [comment]
Ah yes, that was the 1 other thing that was still pending for @olpie101 to do (which is probably why the button wasn't there). We did it for the Delete button #21 
I'll ticket it

**Comment by smn** [comment]
:cake: awesome, thank you.

**Pull request merged**
